### PR TITLE
Design of the Store Manager Login Page

### PR DESCRIPTION
**Pull request by Nicanor008**
**What is this PR?** 
This is a pull request on discusion about a user login page User Interface(UI). It helps users to redirect them to specific pages.
_Like an admin(store manager) will be redirect to admins page after login_

**Technologies I have Used so far**
- HTML for markup of the elements
- CSS for styling of the login elements

A Screen shot of the login have designed

screenshot from 2018-10-08 22-56-59

Let me know what you think about this design.

### CODE REVIEW

**Comment by waracci** [comment]
@Nicanor008 Are you sure you want to merge this PR into master?

**Comment by Nicanor008** [comment]
@waracci not yet there are some changes have made in my local repo, I haven't pushed yet, then I'll merge

**Comment by kwanj-k** [comment]
@Nicanor008 @waracci I think what waracci meant to say is that 
changes or not, dont make a PR to master yet

**Comment by Nicanor008** [comment]
@kwanj-k thanks for the point, I haven't interfered with the master branch.

**Comment by Teatoller** [comment]
Hi Nicanor,
My observation is that your buttons are wordy (verbosity). My fair observation is button having at most two words but ideally one word. Your color theme is cool.

**Comment by Nicanor008** [comment]
@Teatoller yea that's true, let me implement that

**Comment by Nicanor008** [comment]
@kwanj-k message got. @Paulstar200 your thought has some truth, will implement and take a look

**Pull request merged**
